spring:
  datasource:
    url: jdbc:postgresql://monorail.proxy.rlwy.net:29923/railway
    username: postgres
    password: llpeZrvmdcCmEBkMoBcDfGNfIosvpIvh
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true